import { create } from 'zustand'

const EN = {
  // Navigation
  nav_overview:  'OVERVIEW',
  nav_ingest:    'INGEST',
  nav_query:     'QUERY',
  nav_results:   'RESULTS',
  nav_history:   'HISTORY',
  nav_export:    'EXPORT',
  nav_settings:  'SETTINGS',

  // Dashboard
  dash_title:       'Mission Control',
  dash_subtitle:    'StatIQ',
  dash_stat1:       'Datasets Ingested',
  dash_stat2:       'Queries Executed',
  dash_stat3:       'Records Processed',
  dash_stat4:       'Active Dataset',
  dash_activity:    'Activity Stream',
  dash_actions:     'Quick Actions',
  dash_no_dataset:  'No Dataset Loaded',
  dash_upload_to:   'Upload a survey file to initialise analysis',
  dash_init:        'Initialise Dataset',
  dash_launch:      'Launch Query Workspace',

  // Ingestion
  ingest_title:     'Dataset Ingestion',
  ingest_subtitle:  'Upload official survey microdata to begin querying',
  ingest_drop:      'Drag & Drop Dataset File Here',
  ingest_browse:    'Browse Files',
  ingest_success:   'Dataset Ingested Successfully',
  ingest_ready:     'Ready for querying',
  ingest_start:     'Start Querying This Dataset',
  ingest_replace:   'Replace Dataset',
  ingest_preview:   'Data Preview — First 5 Rows',
  ingest_columns:   'Detected Columns',

  // Query
  query_title:      'Query Workspace',
  query_nl:         'Natural Language Query',
  query_builder:    'Visual Query Builder',
  query_ask:        'Ask a question about your dataset',
  query_placeholder:'e.g. Show unemployment rate among rural women in Tamil Nadu...',
  query_run:        'Generate Insights',
  query_running:    'Running...',
  query_examples:   'Example queries',
  query_scoped:     'Query scoped exclusively to',
  query_no_data:    'No Dataset Loaded',
  query_upload_msg: 'Upload a survey dataset before running queries.',
  query_go_upload:  'Upload Dataset',
  query_select_msg: 'Select a survey dataset from the dashboard before running queries.',
  query_go_select:  'Select Dataset',

  // Results
  result_indicator: 'Indicator',
  result_value:     'Result Value',
  result_records:   'Records Analysed',
  result_time:      'Query Time',
  result_meaning:   'What This Means',
  result_confidence:'Query Confidence Score',
  result_formula:   'Formula Used',
  result_sql:       'SQL Query Executed',
  result_how:       'How This Result Was Generated',
  result_trace:     'Query Traceability',
  result_gov:       'Data Governance',
  result_constraint:'Dataset Constraint',
  result_privacy:   'Privacy Status',
  result_explain:   'Query Explanation',
  result_export:    'Export Results',

  // Governance
  gov_constraint_desc: 'Query executed only on active dataset',
  gov_no_external:     'No external sources accessed',
  gov_privacy_safe:    'PRIVACY SAFE',
  gov_suppressed:      'RESULT SUPPRESSED',
  gov_sample_met:      'Sample size ≥ 30 threshold met',
  gov_aggregated:      'Aggregated outputs only · No microdata exposure',

  // Settings
  settings_title:      'Settings',
  settings_appearance: 'Appearance',
  settings_theme:      'Theme Mode',
  settings_light:      'LIGHT',
  settings_dark:       'DARK',
  settings_profile:    'Profile',
  settings_save:       'Save Settings',
  settings_saved:      'Settings updated successfully',
  settings_language:   'Interface Language',
  settings_name:       'Full Name',
  settings_email:      'Email Address',
  settings_dept:       'Department',
  settings_role:       'Role',
  settings_security:   'Security',
  settings_prefs:      'Platform Preferences',

  // Common
  no_results:    'No Results Yet',
  no_results_msg:'Run a query in the Query Workspace to see results here.',
  go_query:      'Go to Query Workspace',
  privacy_safe:  'Privacy Safe',
  sign_out:      'Sign Out',
  active_dataset:'Active Dataset',
  no_dataset:    'No dataset loaded',
  live:          'Live',
  completed:     'Completed',
  loading:       'Processing...',
  loading_sub:   'Applying privacy filters · Generating insights',
  export_csv:    'Download CSV',
  export_json:   'Download JSON',
  export_png:    'Download PNG',
  export_link:   'Copy Shareable Link',
}

const HI = {
  // Navigation
  nav_overview:  'अवलोकन',
  nav_ingest:    'डेटा अपलोड',
  nav_query:     'प्रश्न',
  nav_results:   'परिणाम',
  nav_history:   'इतिहास',
  nav_export:    'निर्यात',
  nav_settings:  'सेटिंग्स',

  // Dashboard
  dash_title:       'मिशन कंट्रोल',
  dash_subtitle:    'MoSPI सर्वेक्षण बुद्धिमत्ता प्लेटफ़ॉर्म',
  dash_stat1:       'डेटासेट अपलोड',
  dash_stat2:       'प्रश्न किए गए',
  dash_stat3:       'रिकॉर्ड प्रोसेस',
  dash_stat4:       'सक्रिय डेटासेट',
  dash_activity:    'गतिविधि स्ट्रीम',
  dash_actions:     'त्वरित कार्य',
  dash_no_dataset:  'कोई डेटासेट नहीं',
  dash_upload_to:   'विश्लेषण शुरू करने के लिए फ़ाइल अपलोड करें',
  dash_init:        'डेटासेट शुरू करें',
  dash_launch:      'प्रश्न कार्यक्षेत्र खोलें',

  // Ingestion
  ingest_title:     'डेटासेट अपलोड',
  ingest_subtitle:  'सर्वेक्षण डेटा अपलोड करें',
  ingest_drop:      'यहाँ फ़ाइल छोड़ें',
  ingest_browse:    'फ़ाइल चुनें',
  ingest_success:   'डेटासेट सफलतापूर्वक अपलोड',
  ingest_ready:     'प्रश्न के लिए तैयार',
  ingest_start:     'इस डेटासेट पर प्रश्न करें',
  ingest_replace:   'डेटासेट बदलें',
  ingest_preview:   'डेटा पूर्वावलोकन — पहली 5 पंक्तियाँ',
  ingest_columns:   'पहचाने गए कॉलम',

  // Query
  query_title:      'प्रश्न कार्यक्षेत्र',
  query_nl:         'सामान्य भाषा प्रश्न',
  query_builder:    'विज़ुअल प्रश्न बिल्डर',
  query_ask:        'अपने डेटासेट के बारे में प्रश्न पूछें',
  query_placeholder:'उदा. तमिलनाडु में ग्रामीण महिलाओं की बेरोज़गारी दर दिखाएं...',
  query_run:        'जानकारी प्राप्त करें',
  query_running:    'चल रहा है...',
  query_examples:   'उदाहरण प्रश्न',
  query_scoped:     'प्रश्न केवल इस डेटासेट पर',
  query_no_data:    'कोई डेटासेट नहीं',
  query_upload_msg: 'प्रश्न चलाने से पहले डेटासेट अपलोड करें।',
  query_go_upload:  'डेटासेट अपलोड करें',
  query_select_msg: 'प्रश्न चलाने से पहले डैशबोर्ड से एक डेटासेट चुनें।',
  query_go_select:  'डेटासेट चुनें',

  // Results
  result_indicator: 'संकेतक',
  result_value:     'परिणाम मूल्य',
  result_records:   'विश्लेषित रिकॉर्ड',
  result_time:      'प्रश्न समय',
  result_meaning:   'इसका अर्थ',
  result_confidence:'विश्वास स्कोर',
  result_formula:   'उपयोग किया गया सूत्र',
  result_sql:       'SQL प्रश्न',
  result_how:       'परिणाम कैसे बना',
  result_trace:     'प्रश्न ट्रेसेबिलिटी',
  result_gov:       'डेटा शासन',
  result_constraint:'डेटासेट बाधा',
  result_privacy:   'गोपनीयता स्थिति',
  result_explain:   'प्रश्न स्पष्टीकरण',
  result_export:    'परिणाम निर्यात',

  // Governance
  gov_constraint_desc: 'केवल सक्रिय डेटासेट पर प्रश्न',
  gov_no_external:     'कोई बाहरी स्रोत नहीं',
  gov_privacy_safe:    'गोपनीयता सुरक्षित',
  gov_suppressed:      'परिणाम दबाया गया',
  gov_sample_met:      'नमूना आकार ≥ 30 पूरा हुआ',
  gov_aggregated:      'केवल एकत्रित आउटपुट · कोई व्यक्तिगत डेटा नहीं',

  // Settings
  settings_title:      'सेटिंग्स',
  settings_appearance: 'दिखावट',
  settings_theme:      'थीम मोड',
  settings_light:      'लाइट',
  settings_dark:       'डार्क',
  settings_profile:    'प्रोफ़ाइल',
  settings_save:       'सेटिंग्स सहेजें',
  settings_saved:      'सेटिंग्स सफलतापूर्वक अपडेट',
  settings_language:   'इंटरफ़ेस भाषा',
  settings_name:       'पूरा नाम',
  settings_email:      'ईमेल पता',
  settings_dept:       'विभाग',
  settings_role:       'पद',
  settings_security:   'सुरक्षा',
  settings_prefs:      'प्लेटफ़ॉर्म प्राथमिकताएं',

  // Common
  no_results:    'अभी कोई परिणाम नहीं',
  no_results_msg:'परिणाम देखने के लिए एक प्रश्न चलाएं।',
  go_query:      'प्रश्न कार्यक्षेत्र पर जाएं',
  privacy_safe:  'गोपनीयता सुरक्षित',
  sign_out:      'साइन आउट',
  active_dataset:'सक्रिय डेटासेट',
  no_dataset:    'कोई डेटासेट नहीं',
  live:          'लाइव',
  completed:     'पूर्ण',
  loading:       'प्रोसेसिंग...',
  loading_sub:   'गोपनीयता फ़िल्टर लागू · जानकारी तैयार',
  export_csv:    'CSV डाउनलोड',
  export_json:   'JSON डाउनलोड',
  export_png:    'PNG डाउनलोड',
  export_link:   'लिंक कॉपी करें',
}

export const LANGS = { en: EN, hi: HI }

export const useLang = create((set, get) => ({
  lang: 'en',
  setLang: (lang) => set({ lang }),
  t: (key) => LANGS[get().lang][key] || LANGS['en'][key] || key,
}))